### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/shelterprotocol.net-old#10]
### Problem

![Screenshot 2023-09-16 at 10 14 38 AM](https://github.com/okTurtles/shelterprotocol.net/assets/138706/ef159df5-2b76-442d-8640-39f2cae64ebc)

We're currently using Astro's favicon.

### Solution

A simple solution is to just remove the favicon entirely.

However a better solution would be to choose some type of simple turtle shell image. For example, something along these lines, but perhaps even simpler (rounder, more abstract and symmetrical):

![artwork](https://github.com/okTurtles/shelterprotocol.net/assets/138706/285aa6c6-3cbe-4e03-8dae-01bca770460a)

**Comment by npxpatel** [comment]
Would like to contribute to it, I have tried to search for index or an html file to fix the favicon but didn't find one. Could you help from where could I make those changes?

**Comment by taoeffect** [comment]
Hi @btrezzy, thanks for offering. It's in `./public/favicon.svg`. Feel free to post any logo ideas you have to this thread and we'll evaluate them / offer feedback.

**Comment by npxpatel** [comment]
Have a loot at this, would be happy to find more variations if needed:

![noun-sea-turtle-4037492](https://github.com/okTurtles/shelterprotocol.net/assets/128296263/acdd207c-eea4-48a9-b811-cd6cd6073ff6)

**Comment by taoeffect** [comment]
@btrezzy Nice! I like how it's symmetrical now. 👍 

Regarding change requests:

- Can you make the head, arms and legs stubbier?
- Can you make the inner shell segments smaller?
- Can you reintroduce the outer black circle/ring?

I've included some crude changes here to show what I mean in terms of the direction, but you can probably do a way better job than I did:

![turtle](https://github.com/okTurtles/shelterprotocol.net/assets/138706/5a4e87cc-7ef7-45c8-886d-f2dbf683f8b2)

Obligatory legal note: by submitting your logo design, you agree to assign all intellectual property rights, including copyrights, in the contributed logo to okTurtles Foundation Inc. in exchange for crediting you (we can include a link on the about page of the Shelter website to your portfolio or personal site if you'd like, just send us your name and link). This allows us to use the logo design in any way we see fit for the project without any further permission from or compensation to you as the contributor. You represent that you have the right to make this assignment and that the logo does not infringe any third party intellectual property rights.
