### ISSUE TITLE
Fix broken back button on Firefox

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/shelterprotocol.net-old#3]
### Problem

On Firefox (and maybe other browsers), when visiting a link to https://shelterprotocol.net, you can't click the back button anymore.

### Solution

This seems to be caused by the way the docs redirect to a localized page: https://github.com/okTurtles/shelterprotocol.net/blob/master/src/pages/index.astro#L4

Figure out a way to redirect that doesn't break the back button on Firefox.

**Comment by jazzyjackson** [comment]
From reading the docs of astro, I believe you should be able to add a redirect value to astro.config.mjs in the project root:

```js
import { defineConfig } from 'astro/config'
import preact from '@astrojs/preact'
import react from '@astrojs/react'
import mdx from '@astrojs/mdx'

// https://astro.build/config
export default defineConfig({
	integrations: [
		// Enable Preact to support Preact JSX components.
		preact(),
		react(),
		mdx()
	],
	site: 'https://shelterprotocol.net',
        redirects: {
          '/': '/en/introduction/'
	}
  }
})
```


via https://docs.astro.build/en/core-concepts/routing/#configured-redirects

**Comment by taoeffect** [comment]
Cool! Thanks @jazzyjackson! Let me give this a try and see if it works...

**Comment by taoeffect** [comment]
Turns out the fix was simpler! Just use `window.location.replace` instead! This also will allow us to dynamically pick the redirect based on the language (if & when we get translated pages!)
